# Generated by Django 4.1.11 on 2023-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_certificate_verified_alter_certificate_issued_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued_on',
            field=models.DateTimeField(),
        ),
    ]
