# Generated by Django 4.1.11 on 2023-11-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_certificate_issued_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('issued_on', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='certificate',
        ),
    ]
