# Generated by Django 4.1.11 on 2023-11-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_certificates_delete_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
