# Generated by Django 4.1.11 on 2023-11-06 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_certificates_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'ordering': ['-issued_on']},
        ),
        migrations.AddField(
            model_name='certificates',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='certificates',
            index=models.Index(fields=['issued_on'], name='mysite_cert_issued__d13d7e_idx'),
        ),
    ]
