# Generated by Django 4.1.11 on 2023-11-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('time', models.DateTimeField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('comments', models.TextField(max_length=250)),
            ],
        ),
    ]
